In [3]:
!pip install pandas

In [4]:
import pandas as pd

In [6]:
df=pd.read_csv('output.csv')

In [7]:
df.head(5)

brand     model transmission  age    fuel  engine       km  owner  \
0  mahindra      thar       manual  4.0  diesel  2184.0  11003.0    1.0   
1   hyundai     verna       manual  6.0  petrol  1591.0  66936.0    1.0   
2      tata   harrier       manual  2.0  diesel  1956.0  27990.0    1.0   
3     honda      city    automatic  1.0  petrol  1498.0   5061.0    1.0   
4      ford  ecosport       manual  3.0  diesel  1498.0  23480.0    1.0   

       price location  mileage  power  seats type  
0  1231000.0      NaN      NaN    NaN    NaN  NaN  
1   786000.0      NaN      NaN    NaN    NaN  NaN  
2  1489000.0      NaN      NaN    NaN    NaN  NaN  
3  1227000.0      NaN      NaN    NaN    NaN  NaN  
4   887000.0      NaN      NaN    NaN    NaN  NaN

In [8]:
1+1

2

In [12]:
## Numpy
import numpy as np

In [13]:
lst=[1,2,3,4]
arr=np.array(lst)

In [14]:
arr

array([1, 2, 3, 4])

In [15]:
type(arr)

numpy.ndarray

In [16]:
arr.shape

(4,)

In [ ]:
arr1=np.array([[1,2,3],[4,5,6]])

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
## 2 dimension
arr1.shape

(2, 3)

In [ ]:
arr1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
arr1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr1.dtype

dtype('int32')

In [ ]:
np.arange(1,20,2).reshape(2,5).shape

(2, 5)

In [ ]:
np.array(range(1,20,2))

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [ ]:
np.linspace(1,20,40).reshape(20,2)

array([[ 1.        ,  1.48717949],
       [ 1.97435897,  2.46153846],
       [ 2.94871795,  3.43589744],
       [ 3.92307692,  4.41025641],
       [ 4.8974359 ,  5.38461538],
       [ 5.87179487,  6.35897436],
       [ 6.84615385,  7.33333333],
       [ 7.82051282,  8.30769231],
       [ 8.79487179,  9.28205128],
       [ 9.76923077, 10.25641026],
       [10.74358974, 11.23076923],
       [11.71794872, 12.20512821],
       [12.69230769, 13.17948718],
       [13.66666667, 14.15384615],
       [14.64102564, 15.12820513],
       [15.61538462, 16.1025641 ],
       [16.58974359, 17.07692308],
       [17.56410256, 18.05128205],
       [18.53846154, 19.02564103],
       [19.51282051, 20.        ]])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones((5,2,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [ ]:
5 + np.ones((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [ ]:
np.eye(6).reshape(12,3)

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])